import type { Metadata } from "next";
import "./globals.css";
import { Quicksand } from "next/font/google";
import { ABeeZee } from "next/font/google";
import { Bungee } from "next/font/google";
import Header from "../components/Header"
const bungee = Bungee({
  subsets: ["latin"],
  weight: ["400"],

  variable: "--font-bungee",
});
//header font
const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-quicksand", 
});
//main font
const abeezee = ABeeZee({
  subsets: ["latin"],
  weight: ["400"], 
  variable: "--font-abeezee",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.variable} ${abeezee.variable} ${bungee.variable}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
